# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estudios',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='experienciaLaboral',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='habilidades',
            field=models.TextField(default=False),
        ),
    ]
