# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20170630_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=50)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
