# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_experiencialaboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='hasta',
            field=models.DateField(blank=True),
        ),
    ]
