# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20170630_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
