# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20170630_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='experienciaLaboral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.ExperienciaLaboral'),
        ),
    ]
