# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20170630_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='experienciaLaboral',
        ),
        migrations.AddField(
            model_name='alumno',
            name='experienciaLaboral',
            field=models.ManyToManyField(to='administracion.ExperienciaLaboral', verbose_name='experiencia laboral'),
        ),
    ]
