# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_auto_20170630_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('area_de_estudio', models.CharField(max_length=100)),
                ('tipoDeEstudio', models.CharField(choices=[('T', 'Tecnico'), ('U', 'Universitario'), ('M', 'Maestría'), ('D', 'Doctorado'), ('O', 'Otro')], max_length=1)),
                ('estado', models.CharField(choices=[('C', 'En curso'), ('G', 'Graduado'), ('A', 'Abandonado')], max_length=1)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='estudios',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='habilidades',
        ),
        migrations.AddField(
            model_name='habilidades',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Alumno'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Alumno'),
        ),
    ]
