# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_auto_20170630_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='myfolder/'),
        ),
    ]
