# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_alumno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidades',
            name='nivel',
            field=models.CharField(choices=[('P', 'Principiante'), ('I', 'Intermedio'), ('A', 'Avanzado')], default='P', max_length=1),
        ),
    ]
