# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_habilidades_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidades',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
