# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_habilidades_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('V', 'Viudo'), ('D', 'Divorciado')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nacionalidad',
            field=models.CharField(default='Peru', max_length=100),
        ),
    ]
