# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_auto_20170707_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(default=''),
        ),
    ]
