# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_auto_20170709_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2017, 7, 9)),
        ),
    ]
