# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_auto_20170709_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
