# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_auto_20170709_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
