# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0022_auto_20170709_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, default='1999-01-01', null=True),
        ),
    ]
